services:
  meeting-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting-frontend
    volumes:
      - ./:/app
    environment:
      - VUE_APP_API=https://meetingapi.daovitou.net
      - VUE_APP_TITLE=Meeting System
    # ports:
    #   - 8080:8080
