services:
  meeting-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting-frontend
    volumes:
      - ./:/app
      - .env:/app/.env
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - VUE_APP_API=https://meetingapi.daovitou.net
      - VUE_APP_TITLE=Meeting System
    ports:
      - 8080:8080
